---
include:
  - project: 'sre/iac/ci'
    ref: master
    file:
      - 'hidden/buildkit.yml'

stages:
  - PreTest
  - Build

variables:
  VERSION: $CI_COMMIT_TAG
  GOLANG_VERSION: "1.17"


.buildkit:
  variables:
    BUILDKIT_CUSTOM_ARGS: "--opt build-arg:VERSION=${VERSION} --opt build-arg:GOLANG_VERSION=${GOLANG_VERSION}"

golang-lint:
  stage: PreTest
  script:
    - docker pull golangci/golangci-lint:latest
    - docker run --rm -v "$PWD":/app -w /app golangci/golangci-lint:latest golangci-lint --color always run

image build and push:
  extends: .buildkit
  stage: Build
  only:
    - tags
    - develop
  tags:
    - infrastructure
