{
 "title": "SberCDN",
 "tags": [ "CDN" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Certificates valid days",
   "type": "gauge",
   "gridPos": { "h": 24, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sbercdn_certificate_valid_till - time())",
     "legendFormat": "{{cn}}"
    }
   ]
  },
  {
   "title": "Traffic by resource",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sbercdn_traffic", "legendFormat": "Totall" },
    { "expr": "sbercdn_resource_traffic", "legendFormat": "{{resource}}" }
   ]
  },
  {
   "title": "Bandwidth by resource",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "sbercdn_bandwidth", "legendFormat": "Total" },
    { "expr": "sbercdn_resource_bandwidth", "legendFormat": "{{resource}}" }
   ]
  },
  {
   "title": "Cache ratio by resource",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "sbercdn_cache_ratio", "legendFormat": "Total" },
    { "expr": "sbercdn_resource_cache_ratio", "legendFormat": "{{resource}}" }
   ]
  },
  {
   "title": "Hits by resource",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sbercdn_hits", "legendFormat": "Total" },
    { "expr": "sbercdn_resource_hits", "legendFormat": "{{resource}}" }
   ]
  },
  {
   "title": "Cache ratio by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "sbercdn_cache_ratio", "legendFormat": "Total" },
    { "expr": "sbercdn_code_cache_ratio", "legendFormat": "{{code}}" }
   ]
  },
  {
   "title": "Hits by code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sbercdn_hits", "legendFormat": "Total" },
    { "expr": "sbercdn_code_hits", "legendFormat": "{{code}}" }
   ]
  }
 ]
}